@startuml

rectangle ResultBase
rectangle ResultCapture
rectangle StartableResultCapture
rectangle Future

ResultBase <|-- ResultCapture
ResultBase <|-- Future
ResultCapture <|-- StartableResultCapture

@enduml